version: '3.8'

services:
  web:
    build: .
    container_name: deepinteractome_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
